### ISSUE TITLE
trouble

### ISSUE THREAD

**Issue by hetocarvalho** [ScottKbka/avi_glitching#1]
Hi,

sorry for the english

Ive just installed this avi_glitch with ruby after have installed the aviglitch(that works fine)..

I used all passes described in installation process (using windows os) but I try to access glitch all command in prompt and received this error message: 'glitch' isnt recocnized file format, them I tryed to put in the same prompt  cd>ruby glitch all  , and received the same error.

Ive installed ruby and gems, that works fine with aviglitch.

whats the trouble? can you help? Im trying to glitch videos with glitch utilities and that isn't recognizable

**Comment by ScottKbka** [comment]
@hetocarvalho I haven't tested this on Window, so I don't know if all the commands will work. in the Read Me it says "Clone this repo into your scripts directory and add avi_glitching/bin to your $PATH." I'm sure there's a similar command for Windows.

If you wish, you can probably change glitch to glitch.rb then `cd` into the bin and run `ruby PATH_TO_AVI_GLITCHING/bin/glitch.rb`. That might work.

**Comment by hetocarvalho** [comment]
now it works in parts but I received the following error: 

>>>> broken.avi <<<<
melting at frame 1
C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn': Exec format error - melt.rb "_INPUT_DIR/broken.avi" -s "1" -o "_OUTPUT_DIR/13-47-8_E4_melt/broken_E4_sf_1.mov" (Errno::ENOEXEC)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:32:in `spawn'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line/runners/process_runner.rb:21:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:136:in `execute'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:75:in `run'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:145:in `block in melt'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:142:in `times'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:142:in `melt'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:297:in `block in run'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:290:in `foreach'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:290:in `run'
        from C:/Users/heto/Documents/ruby scripts/avi_glitching-master scott/bin/glitch.rb:334:in `<main>'

it creates the output dir, but no one glitched file in. (Errno::ENOEXEC)   do you know what it means?  thanks in advice

**Comment by ScottKbka** [comment]
Check out the dependencies in the readme. You need FFMpeg installed. You might also need to edit the command line scripts to match your OS.

**Comment by hetocarvalho** [comment]
sorry for the inconvenient, im just asking this to the japanese developer too,

Ive just installed the ffmpeg via scoop (in windows, a brew option) then installed the gifsicle too.  the batch creates the ouput dir, with another dir respective of command inputed, but theres no video inside, and show some error. in the bin I have input_dir + files catched on github: concat, ghost, etc.

can you send a printscreen of the batch in macos?  thanks

**Comment by ScottKbka** [comment]
What error do you get? There are a bunch of things that could be causing this. Did you `bundle install`? Is FFmpeg accessible via `ffmpeg -i :infile -an -q:v 0 :outfile` in the terminal? Are the files in the bin executable?

**Comment by hetocarvalho** [comment]
yes, Ive just installed ffmpeg (before I guess that is the build that I was using that was broked, but not) 
them download gifsicle and put on the root directory, put a folder in the root directory _INPUT_DIR with all .avi files, open up a terminal them cd in root directory, (unitl this process I haved installed the aviglitch gem, and it works fine) in the terminal root put glitch all... what happens is that it creates an Output_DIR in the root, with a subfolder random named, but nothing inside. them the terminal goes error, following: 

################################################

         Glitching 15 files

################################################



################################################

                  E1

################################################
>>>> *.avi <<<<

starting at frame 2 with 2 loop frames
C:/Ruby22/lib/ruby/gems/2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:77:in `rescue in run': No such file or directory - twitch.rb "_INPUT_DIR/broken.avi" -s "2" -l "2" --ghost -o "_OUTPUT_DIR/16-24-23_E1_tweaking/broken_E1_sf_2_lf_2.mov" (Cocaine::CommandNotFoundError)
        from (my $PATH)

them I dont know if it means no such file or directory twitch.rb (that exists in the root) or the error is in the cocaine gem. what do you think? remember it creates an empty folder _output

I tried with various files (because i guess there any format that ffmpeg dont accept) but it wont works. 

thanks for the patience.

**Comment by ScottKbka** [comment]
It is looking for the scripts in the bin directory. All of these need to be in your $PATH. I'm not familiar with Windows, but you could try adding `export PATH="$PATH:/FULL/PATH/TO/aviglitch-utils/bin"` to your .bashrc or just run that command before you try `glitch all`.

Basically the `glitch` script was written to glitch videos in batches. You can use twitch.rb or melt.rb or any of the other ones on their own and they will create one glitched file.
